import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";
import "./globals.css";
import { Header } from "@/components/header/header";
import { Mulish } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";

const mulish = Mulish({ subsets: ["latin"], weight: "900" });

export const metadata: Metadata = {
  title: "ЕТ Автоматика",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await auth();
  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body className={mulish.className}>
          <Header />
          {children}
          <Toaster />
        </body>
      </html>
    </SessionProvider>
  );
}
